/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'Tests',
      collapsed: false,
      items: ['test/test1']
    },
    {
      type: 'category',
      label: 'Documentation',
      collapsed: false,
      items: ['intro', 'intro/platform']
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/data-from-s3', 'guides/data-from-s3-to-iomete', 'guides/data-from-jdbc', 'guides/run-spark-job']
    }
  ],

  // guide: ['guide', 'guide/guide1', 'guide/guide2', 'guide/guide3', 'guide/guide4'],
};

module.exports = sidebars;
