/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guides: [
    {
      type: "category",
      label: "User Guide",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Compute Clusters",
          collapsed: false,
          items: [
            "compute-clusters/overview",
            "compute-clusters/creating-clusters",
            "compute-clusters/managing-clusters",
          ],
        },
        "event-stream",
        "spark-jobs",
        {
          type: "category",
          label: "SQL Editor",
          collapsed: true,
          items: [
            "sql-editor/overview",
            "sql-editor/workspaces",
            {
              type: "category",
              label: "Worksheets",
              collapsed: true,
              items: [
                "sql-editor/worksheets",
                "sql-editor/running-queries",
                "sql-editor/query-results",
                "sql-editor/collaboration",
              ],
            },
            "sql-editor/database-explorer",
            "sql-editor/database-explorer-api-migration",
            "sql-editor/query-history",
            "sql-editor/dashboards",
            "sql-editor/scheduling",
          ],
        },
        {
          type: "category",
          label: "Data Catalog",
          collapsed: true,
          items: [
            "data-catalog/overview",
            "data-catalog/search",
            "data-catalog/data-explorer",
            "data-catalog/favorites",
            "data-catalog/table-details",
            "data-catalog/classification-tags",
            "data-catalog/access-permissions",
          ],
        },
        "create-a-personal-access-token",
        "global-spark-settings",
        "private-docker-registry",
        "docker-tag-aliases",
        "email-settings",
        {
          type: "category",
          label: "Node Types",
          collapsed: true,
          items: [
            "node-types/overview",
            "node-types/spark-resource-selection",
            "node-types/internal-implementation",
            "node-types/default-node-types",
            "node-types/performance-benchmarking",
            "node-types/node-type-sizing",
          ],
        },
        "volumes",
        "secrets",
        "api-reference",
        "register-table",
        "storage-configs",
        "system-tables",
      ],
    },
    {
      type: "category",
      label: "Identity and Account",
      collapsed: true,
      items: [
        "iam/users",
        "iam/groups",
        "iam/roles",
        "iam/ldap-configuration",
        {
          type: "category",
          label: "SSO Configuration",
          collapsed: false,
          items: [
            "iam/sso/sso",
            "iam/sso/sso-saml",
            "iam/sso/sso-oidc",
            "iam/sso/sso-okta",
            "iam/sso/sso-onelogin",
            "iam/sso/sso-entra-id",
            "iam/sso/scim",
            "iam/sso/scim-okta",
          ],
        },

        "iam/ras/ras",
        "iam/domain-authorization",
      ],
    },
    {
      type: "category",
      label: "Spark Catalogs",
      collapsed: true,
      items: [
        "spark-catalogs/overview",
        {
          type: "category",
          label: "IOMETE Managed Catalogs",
          collapsed: false,
          items: [
            "spark-catalogs/internal",
            "spark-catalogs/enterprise",
          ],
        },
        {
          type: "category",
          label: "External Catalogs",
          collapsed: false,
          items: [
            "spark-catalogs/external-jdbc",
            "spark-catalogs/external-rest",
            "spark-catalogs/external-glue",
            "spark-catalogs/external-nessie",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Spark Settings",
      collapsed: true,
      items: ["spark-settings/overview"],
    },
    {
      type: "category",
      label: "Data Sources",
      collapsed: true,
      items: [
        "reference/data-sources/jdbc-sources",
        "reference/data-sources/snowflake-connector",
        "reference/data-sources/csv-files",
        "reference/data-sources/json-files",
        "reference/data-sources/parquet-files",
        "reference/data-sources/orc-files",
      ],
    },
    {
      type: "category",
      label: "Data Security",
      collapsed: true,
      items: [
        "data-security/overview",
        "data-security/access-policy",
        "data-security/data-masking",
        "data-security/row-level-filter",
        "data-security/tag-based-access-policy",
        "data-security/tag-based-data-masking",
        "data-security/data-security-api",
        "data-security/classifications",
        "data-security/classification-best-practices",
      ],
    },
    {
      type: "category",
      label: "Spark Jobs",
      collapsed: true,
      items: [
        "spark-job/getting-started",
        "spark-job/spark-application-config",
        "spark-job/iomete-sdk",
        "spark-job/airflow",
        "spark-job/nessie-integration",
        "spark-job/spark-logging",
        "spark-job/job-orchestrator",
      ],
    },
    {
      type: "category",
      label: "Jupyter Containers",
      collapsed: true,
      items: [
        "notebook/jupyter-containers",
        "notebook/manage-containers",
        "notebook/using-jupyterlab",
      ],
    },
    {
      type: "category",
      label: "Table Maintenance (Beta)",
      collapsed: true,
      items: [
        "table-maintenance/overview",
        "table-maintenance/catalog-configuration",
        "table-maintenance/table-configuration",
        "table-maintenance/advanced-configuration",
        "table-maintenance/run-history-and-metrics",
        "table-maintenance/deployment",
        "table-maintenance/faqs",
      ],
    },
    {
      type: "category",
      label: "Client & Libraries",
      collapsed: true,
      items: [
        "driver/sql-alchemy-driver",
        "driver/jdbc-driver",
      ],
    },
    {
      type: "category",
      label: "AWS",
      collapsed: true,
      items: ["aws/s3-bucket-permissions", "aws/glue-catalog-permissions"],
    },
    {
      type: "category",
      label: "GCP",
      collapsed: true,
      items: ["gcp/gcs-bucket-permissions"],
    },
    {
      type: "category",
      label: "Kubernetes",
      collapsed: true,
      items: [
        "k8s/private-docker-registry",
        "k8s/spark-executor-shuffle-storage-options",
        "k8s/sizing-nodes-in-kubernetes-for-iomete-installation",
        "k8s/cpu-vs-vcpu",
        "k8s/monitoring",
        "k8s/database-migration",
      ],
    },
    {
      type: "category",
      label: "Misc",
      collapsed: true,
      items: [
        "misc/datagrip-lakehouse-connection",
        "misc/shutdown-for-maintenance",
      ],
    },
    {
      type: "category",
      label: "Troubleshooting",
      collapsed: true,
      items: [
        "troubleshooting/troubleshooting-lakehouse-oom",
        "troubleshooting/sql-query-errors",
      ],
    },
  ],
};

export default sidebars;
