name: Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --no-progress --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
