name: Build Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --no-progress --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
