name: Docs Deployment V3

on: workflow_dispatch

jobs:
  production:
    name: documentation-deployment-v3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install --no-progress --frozen-lockfile
      - run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.s3_bucket_region }}

      - name: S3 Sync
        run: |
          aws s3 sync build/ s3://${{ secrets.s3_bucket_name }}/resources \
            --delete \
            --cache-control "max-age=86400"

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.cloudfront_distribution_id }} \
            --paths "/resources/*"
