name: Repo maintenance

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  issues: write

jobs:
  stale:
    uses: iomete/.github/.github/workflows/repo-maintenance.yml@main
    with:
      runs-on: ubuntu-latest
